version: '3.4'

services:
  gradeo.db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "Passw0rd."
        ACCEPT_EULA: "Y"
  redis:
    image: redis
    ports:
        - 6379:6379